# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mydesign.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 457)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(360, 0, 241, 431))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.my_table = QtWidgets.QTableWidget(self.groupBox_3)
        self.my_table.setGeometry(QtCore.QRect(10, 20, 221, 401))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.my_table.setFont(font)
        self.my_table.setRowCount(1)
        self.my_table.setColumnCount(2)
        self.my_table.setObjectName("my_table")
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 127))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.my_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.my_table.setItem(0, 1, item)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 0, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.num_75 = QtWidgets.QPushButton(self.groupBox_4)
        self.num_75.setGeometry(QtCore.QRect(260, 20, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.num_75.setFont(font)
        self.num_75.setObjectName("num_75")
        self.num_50 = QtWidgets.QPushButton(self.groupBox_4)
        self.num_50.setGeometry(QtCore.QRect(200, 20, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.num_50.setFont(font)
        self.num_50.setObjectName("num_50")
        self.num_25 = QtWidgets.QPushButton(self.groupBox_4)
        self.num_25.setGeometry(QtCore.QRect(140, 20, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.num_25.setFont(font)
        self.num_25.setObjectName("num_25")
        self.num_10 = QtWidgets.QPushButton(self.groupBox_4)
        self.num_10.setGeometry(QtCore.QRect(80, 20, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.num_10.setFont(font)
        self.num_10.setObjectName("num_10")
        self.num_5 = QtWidgets.QPushButton(self.groupBox_4)
        self.num_5.setGeometry(QtCore.QRect(20, 20, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.num_5.setFont(font)
        self.num_5.setObjectName("num_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 120, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 140, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.free_place = QtWidgets.QLabel(self.centralwidget)
        self.free_place.setGeometry(QtCore.QRect(150, 120, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        self.free_place.setFont(font)
        self.free_place.setObjectName("free_place")
        self.occ_place = QtWidgets.QLabel(self.centralwidget)
        self.occ_place.setGeometry(QtCore.QRect(130, 140, 221, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        self.occ_place.setFont(font)
        self.occ_place.setObjectName("occ_place")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 60, 261, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.ok_btn = QtWidgets.QPushButton(self.centralwidget)
        self.ok_btn.setGeometry(QtCore.QRect(10, 400, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        self.ok_btn.setFont(font)
        self.ok_btn.setObjectName("ok_btn")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 60, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.perc_99 = QtWidgets.QPushButton(self.groupBox_5)
        self.perc_99.setGeometry(QtCore.QRect(230, 20, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.perc_99.setFont(font)
        self.perc_99.setObjectName("perc_99")
        self.perc_25 = QtWidgets.QPushButton(self.groupBox_5)
        self.perc_25.setGeometry(QtCore.QRect(50, 20, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.perc_25.setFont(font)
        self.perc_25.setObjectName("perc_25")
        self.perc_50 = QtWidgets.QPushButton(self.groupBox_5)
        self.perc_50.setGeometry(QtCore.QRect(110, 20, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.perc_50.setFont(font)
        self.perc_50.setObjectName("perc_50")
        self.perc_70 = QtWidgets.QPushButton(self.groupBox_5)
        self.perc_70.setGeometry(QtCore.QRect(170, 20, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.perc_70.setFont(font)
        self.perc_70.setObjectName("perc_70")
        self.linear_btn = QtWidgets.QPushButton(self.centralwidget)
        self.linear_btn.setGeometry(QtCore.QRect(10, 170, 161, 23))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.linear_btn.setFont(font)
        self.linear_btn.setObjectName("linear_btn")
        self.quadratic = QtWidgets.QPushButton(self.centralwidget)
        self.quadratic.setGeometry(QtCore.QRect(180, 170, 161, 23))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.quadratic.setFont(font)
        self.quadratic.setObjectName("quadratic")
        self.double_hash = QtWidgets.QPushButton(self.centralwidget)
        self.double_hash.setGeometry(QtCore.QRect(100, 200, 161, 23))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.double_hash.setFont(font)
        self.double_hash.setObjectName("double_hash")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 230, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 260, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(250, 260, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(180, 280, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 362, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Хеширование"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Таблица"))
        __sortingEnabled = self.my_table.isSortingEnabled()
        self.my_table.setSortingEnabled(False)
        self.my_table.setSortingEnabled(__sortingEnabled)
        self.groupBox_4.setTitle(_translate("MainWindow", "Размер таблицы"))
        self.num_75.setText(_translate("MainWindow", "20к"))
        self.num_50.setText(_translate("MainWindow", "17к"))
        self.num_25.setText(_translate("MainWindow", "15к"))
        self.num_10.setText(_translate("MainWindow", "13к"))
        self.num_5.setText(_translate("MainWindow", "10к"))
        self.label.setText(_translate("MainWindow", "Свободное место: "))
        self.label_2.setText(_translate("MainWindow", "Занатое место:"))
        self.free_place.setText(_translate("MainWindow", "0"))
        self.occ_place.setText(_translate("MainWindow", "0"))
        self.ok_btn.setText(_translate("MainWindow", "ок"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Рандомное заполнение таблицы на:"))
        self.perc_99.setText(_translate("MainWindow", "100%"))
        self.perc_25.setText(_translate("MainWindow", "25%"))
        self.perc_50.setText(_translate("MainWindow", "50%"))
        self.perc_70.setText(_translate("MainWindow", "75%"))
        self.linear_btn.setText(_translate("MainWindow", "Линейный поиск"))
        self.quadratic.setText(_translate("MainWindow", "Квадратичный  поиск"))
        self.double_hash.setText(_translate("MainWindow", "Двойное хеширование"))
        self.label_3.setText(_translate("MainWindow", "Результат:"))
        self.label_4.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "0"))
        self.pushButton.setText(_translate("MainWindow", "Поиск"))


